### ISSUE TITLE
导入图片生成二维码存在无法识别的情况

### ISSUE THREAD

**Issue by yifanzheng** [AJLoveChina/awesome-qrcode#2]
hi, AJLoveChina.  
我在使用你写的这个二维码生成工具时，发现该工具对使用黑白色的图片生成二维码的支持不是很好，存在生成的有些二维码无法识别。 
    
这里我提供两张测试图片：  
![IMG_3798](https://user-images.githubusercontent.com/22571230/69494619-d9faec00-0ef8-11ea-897c-ca0922462320.JPG)
![woman-735754_1920](https://user-images.githubusercontent.com/22571230/69494620-da938280-0ef8-11ea-9062-f8ea61e2ef4e.jpg)  

使用该工具生成的二维码：  
![awesome-qrcode (1)](https://user-images.githubusercontent.com/22571230/69494633-ff87f580-0ef8-11ea-8954-60bef5a0499c.png)
![awesome-qrcode (2)](https://user-images.githubusercontent.com/22571230/69494634-00208c00-0ef9-11ea-9ff9-dac78863eaa9.png)

**Comment by AJLoveChina** [comment]
确实有这个问题，这个正在fix中，还有图片尽量要正方形 效果会好一些
